# Generated by Django 3.0.4 on 2020-03-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
