# Generated by Django 3.0.2 on 2020-03-31 17:36

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0005_bid_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created_by',
            field=models.ForeignKey(default=crum.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
