# Generated by Django 3.0.2 on 2020-04-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20200404_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Bid'),
        ),
    ]
