POST http://172.31.80.164:9999/v1/auctionItem/
Authorization: 'Bearer D9z1iOwcPFprJUlF62dDc3oNrVHHNX'
Content-Type: application/json

{
    "title": "Sheep",
    "description": "Ones with 4 legs",
    "price": 100.0,
    "endDate": "2020-03-13T10:10:00Z"
}